### ISSUE TITLE
[Book Feedback] ePub version

### ISSUE THREAD

**Issue by phaselden** [dotnet-architecture/eBooks#11]
.NET Microservices: Architecture for Containerized .NET Applications)

**What do you think could be improved in this book?**
When showing the table of contents on an iPad (ePub version), all headings at the same level.  The structure of the doc would be very helpful. 

Also, when showing the PDF in Adobe Reader (on Windows) there is no Table of Contents available on the left side to ease navigation.

Just started reading but the content seems great so far. Thanks!

**Comment by nishanil** [comment]
Thanks for the feedback, @phaselden ! 
@mvelosop Probably, something about fine-tuning the tool to address TOC on pdf?

**Comment by mvelosop** [comment]
Hi @phaselden Thanks for the feedback!

The PDF TOC issue has been addressed for the next release of the microservices guide coming out in short.

There's now a a bookmark tree on the left side panel built from the TOC and the TOC items themselves are now links to the section.

Will explore the e-pub version next week.

Hope this helps.

**Comment by mvelosop** [comment]
Hi @phaselden,

The updated PDF version is now available for download from the [Architecture Guidance site](https://dotnet.microsoft.com/learn/aspnet/microservices-architecture) (and everywhere else) 😊

**Comment by phaselden** [comment]
Excellent! Thanks @mvelosop !
