### ISSUE TITLE
[Book Feedback]I cannot download this Microsoft eBook onto my Apple iPad, is this just another problem with GitHub!

### ISSUE THREAD

**Issue by Johnvan** [dotnet-architecture/eBooks#126]
**Please provide the title of the book**
For e.g. "Architecting Cloud-Native .NET Apps for Azure". Assign a corresponding label (if applicable)

**What do you think could be improved in this book?**
A clear and concise description of the changes you would like to see in the final release of the book [...]. 

**What do you like about this book?**
A clear and concise description of the chapters and sections you like in this book.

**Additional context**
Add any other context or screenshots about your feedback.

**Comment by sughosneo** [comment]
Hi @Johnvan, thank you for your feedback. 

Could you please share the link from where you were trying to downloads?
As an alternative, could you please try this [link](https://dotnet.microsoft.com/download/e-book/cloud-native-azure/pdf) and see if that helps?

**Comment by sughosneo** [comment]
Hi @Johnvan, I am closing this issue as of now. Please feel free to reopen if needed. Thank you.
