### ISSUE TITLE
please fill bookmarks in PDFs

### ISSUE THREAD

**Issue by enihcam** [dotnet-architecture/eBooks#163]
as title. thx.

**Comment by erjain** [comment]
Please provide the title of the book
For e.g. "Architecting Cloud-Native .NET Apps for Azure". Assign a corresponding label (if applicable)

What do you think could be improved in this book?
A clear and concise description of the changes you would like to see in the final release of the book [...].

Additional context
Add any other context or screenshots about your feedback.

**Comment by erjain** [comment]
I am closing this issue as of now. Please feel free to reopen it, if needed.
