### ISSUE TITLE
please translate the book into Turkish

### ISSUE THREAD

**Issue by ZilanTuran6** [dotnet-architecture/eBooks#165]
**Please provide the title of the book**
For e.g. "Architecting Cloud-Native .NET Apps for Azure". Assign a corresponding label (if applicable)

**What do you think could be improved in this book?**
A clear and concise description of the changes you would like to see in the final release of the book [...]. 

**What do you like about this book?**
A clear and concise description of the chapters and sections you like in this book.

**Additional context**
Add any other context or screenshots about your feedback.

**Comment by erjain** [comment]
Hi @ZilanTuran6, Thanks for posting your query. Right now we are able to generate the ebook in English Language only, and we have very less requests for the Turkish Language. I am closing this issue as of now, let us know if you have any more queries.
