### ISSUE TITLE
[Book Feedback]

### ISSUE THREAD

**Issue by jasonrpeterson** [dotnet-architecture/eBooks#178]
Enterprise Application Patterns Using .NET MAUI

Minor typo on Page 22 (Page 30 in the PDF)  - From context, minor issue where The should be This.   

At runtime, the container must know which implementation of the services are being requested in 
order to instantiate them for the requested objects. In the eShopOnContainers multi-platform app, 
the IAppEnvironmentService, IDialogService , INavigationService, and ISettingsService
interfaces need to be resolved before it can instantiate a ProfileViewModel object. **The** involves the 
container performing the following actions

**Comment by erjain** [comment]
Hi @jasonrpeterson, nice catch. PR has been raised to fix this in docs: https://github.com/dotnet/docs/pull/30926, ebook will be updated after merging of PR

**Comment by erjain** [comment]
PR has been merged into docs.
