### ISSUE TITLE
[Book Feedback] epub format 

### ISSUE THREAD

**Issue by gpcaretti** [dotnet-architecture/eBooks#181]
Why don't you provide an ePub format of all this so interesting books?

**Comment by erjain** [comment]
Unfortunately, we won't be able to provide epub format right now, we have very less ask to generate a format other than pdf or especially for small screens. In case if you want to read on smaller screens or want to convert to other formats, you can also checkout the markdown files here: https://github.com/dotnet/docs/tree/main/docs/architecture. Thank you.
