### ISSUE TITLE
[Book Feedback]

### ISSUE THREAD

**Issue by andyjballgit** [dotnet-architecture/eBooks#19]
**Please provide the title of the book**
Blazor for ASP .NET Web Forms Developers

**What do you think could be improved in this book?**
A clear and concise description of the changes you would like to see in the final release of the book 
I went through the "Forms and Validation" example and it worked fine but it triggered the thought "the UI looks rubbish for the errors, looks a bit rubbish , basic"  , so it would be good to have a section describing how you could make it look better / more modern UI like below 

[https://cvlrsnergpublic001.blob.core.windows.net/public/NiceUI.jpg
](url)

**What do you like about this book?**
As a Web Forms hack , ive found solutions in the book that I couldn't find in Google .. ie how to do Response.Redirect equivalent , so good stuff . 

**Additional context**
It would be nice to have a cheat sheet , ie like the Response.Redirect example above . Top 20 or so thing u do in Web Forms , and the equivalent thing in Blazor

I come from a Backend, Infrastructure / DevOps background and Web Forms made it very easy for me to quickly produce functional web sites , linking to SQL etc with very little knowledge , understanding of ViewState, Html , CSS, javascript . 

Seems to me with Blazor , you have to understand html , CSS and all this stuff. So anything to ease this transition would be good. 

thanks again 
Andy.

**Comment by nishanil** [comment]
Thanks @andyjballgit for the detailed feedback. 
Keeping the authors looped in: @danroth27 @csharpfritz @twsouthwick
