### ISSUE TITLE
[Book Feedback] Save as epub

### ISSUE THREAD

**Issue by bellons91** [dotnet-architecture/eBooks#192]
Applied to all ebooks

It would be useful to have the possibility to download the ebooks in other formats such as Epub, Mobi, and so on.

The PDF format is not suitable for most  ebook readers nor for smartphone apps (because, for example, it's not possible to change the text size or the font)

**Comment by erjain** [comment]
Hi @bellons91, Unfortunately, we won't be able to provide epub format right now, we have very few ask to generate a format other than pdf or especially for small screens. If you want to read on smaller screens or convert to other formats, you can also check out the markdown files here: https://github.com/dotnet/docs/tree/main/docs/architecture. Thank you.
