### ISSUE TITLE
[Book Feedback]

### ISSUE THREAD

**Issue by SaiUpendranath-Allagadda-swi** [dotnet-architecture/eBooks#193]
**Please provide the title of the book**
Enterprise Application Patterns Using .NET MAUI

Not able to download the book. Got to know about the book from this [site](https://learn.microsoft.com/en-us/dotnet/architecture/maui/).

**Comment by erjain** [comment]
Hi @SaiUpendranath-Allagadda-swi, Thanks for posting here. You can download it from page[ .NET MAUI Architecture Guidance](https://dotnet.microsoft.com/en-us/learn/maui/architecture)  using link of [Download PDF](https://dotnet.microsoft.com/en-us/download/e-book/maui/pdf). I am closing this issue, however, feel free to post here in case of more queries.
