### ISSUE TITLE
Architecting-Modern-Web-Applications-with-ASP.NET-Core-and-Azure.pdf

### ISSUE THREAD

**Issue by sjohag** [dotnet-architecture/eBooks#2]
Under heading Razor Components on page 8.
"executed client-side using a JavaScript library called WebAssembly"
is not true, WebAssembly is an modern, type safe and fast alternative to JavaScript, it is not a JavaScript library.

**Comment by nishanil** [comment]
I think this PR (https://github.com/dotnet/docs/pull/15400 ) should fix this.

**Comment by api-gov-network** [comment]
spam

**Comment by api-gov-network** [comment]
No issue

**Comment by ardalis** [comment]
Agreed - this is fixed now.
