### ISSUE TITLE
[Book Feedback] Can't see code samples in epub or mobi format

### ISSUE THREAD

**Issue by vchircu** [dotnet-architecture/eBooks#20]
**Please provide the title of the book**
"NET Microservices: Architecture for Containerized .NET Applications"

**What do you think could be improved in this book?**
Links to code samples are broken in mobi and epub formats. For example, in chapter 5, under the "Multi-stage builds in Dockerfile" heading, on page 82 of the PDF, there is an example of a Dockerfile. When I open the epub or mobi formats, the link is broken and I can't see the Dockerfile. 

**Additional context**
![image](https://user-images.githubusercontent.com/3405641/75088088-33eb6c00-5551-11ea-903b-0478dd26f1bd.png)

**Comment by nishanil** [comment]
Thanks for the feedback, @vchircu! Apparently, the vendors who helped us provide the mobile formats couldn't fix the issue. Our source for both PDF and the mobile formats are the markdown files in docs hence we are exploring tools that can automate this. Until we figure this out, we will be unable to support the mobile formats in the newer releases :( Sorry! We recommend downloading PDF instead.

**Comment by farajfarook** [comment]
Any updates on this issue? I would love to have the mobi version.

**Comment by vip32** [comment]
@nishanil Any updates on this issue? EPUB is much nicer on ereader

**Comment by nishanil** [comment]
Unfortunately, we are unable to add mobile formats to our books at this time. The demand is also very low :( If anyone is interested to work on this, feel free to send us a PR to this repo with mobile formats from the markdown files generated from here:  https://github.com/dotnet/docs/tree/main/docs/architecture We also need to ensure that the generated books are in sync with the docs.

**Comment by kimjamia** [comment]
It was pretty easy to get a "good enough" MOBI file from the MD files. I cut corners a bit but here's what I did:
1. Copied the contents of all media folders of the book to the root of the book. E.g. `architecture/microservices/container-docker-introduction/media` to `architecture/microservices/media`. Maybe there's a way to use relative paths properly but I just wanted a MOBI file quick.
2. ` pandoc -o book.epub <all-of-the-md-files-mentioned-in-toc.yml>` E.g. `pandoc -o book.epub index.md container-docker-introduction/index.md container-docker-introduction/docker-defined.md ...`
3. Used Calibre to convert EPUB to MOBI.

Software needed:
* [Pandoc](https://pandoc.org/installing.html)
* [Calibre](https://calibre-ebook.com/download)
