### ISSUE TITLE
[Book Feedback] Very good contents to start with if you are in forest of IT.

### ISSUE THREAD

**Issue by mukundkumar83** [dotnet-architecture/eBooks#24]
**Please provide the title of the book**
For e.g. "Architecting Cloud-Native .NET Apps for Azure". Assign a corresponding label (if applicable)

**What do you think could be improved in this book?**
A clear and concise description of the changes you would like to see in the final release of the book [...]. 

**What do you like about this book?**
Azure Native and link to other content to read.

**Comment by nishanil** [comment]
Thanks for the feedback :)
