### ISSUE TITLE
MOBI/ format for current version of microservices ebook

### ISSUE THREAD

**Issue by black-snake** [dotnet-architecture/eBooks#27]
Hi there,

thanks for your great ebooks on Microsoft technologies.

I am very fond of reading the microservices ebook and I recently found out that there is an updated version of it available for MS .NET Core 3.1:
https://github.com/dotnet-architecture/eBooks/blob/master/current/microservices/NET-Microservices-Architecture-for-Containerized-NET-Applications.pdf

So far, there have been the following formats for the book:
- EPUB
- MOBI
- AZW3
- PDF

However, the current version for MS .NET Core 3.1 is available as PDF only. So, could you also provide the ebook in the other formats mentioned above? It is way more convenient to read MOBI or EPUB on an ebook reader instead of a PDF file.

Thanks again.

**Comment by vip32** [comment]
where are the EPUBs?

**Comment by buddystein** [comment]
Epubs?

**Comment by nishanil** [comment]
Unfortunately, we are unable to add mobile formats to our books at this time. The demand is also very low :( If anyone is interested to work on this, feel free to send us a PR to this repo with mobile formats from the markdown files generated from here: https://github.com/dotnet/docs/tree/main/docs/architecture We also need to ensure that the generated books are in sync with the docs.

**Comment by vip32** [comment]
How was this done in the past? Have no experience, but how hard can md>epub
be?

**Comment by nishanil** [comment]
We had a vendor who created this. I am not sure how they did it. For PDF we rely on pandoc and a custom tool to configure it correctly.

**Comment by erjain** [comment]
Considering the original question has been answered, I am closing this issue as of now. Please feel free to reopen if needed. Thank you.
