### ISSUE TITLE
[Book Feedback]

### ISSUE THREAD

**Issue by DuanShaolong** [dotnet-architecture/eBooks#28]
**Microservices architecture e-book**
Can't download[...]. 
![image](https://user-images.githubusercontent.com/19683994/79627365-1a8a2900-816a-11ea-8412-be1a26c62d2d.png)

**Comment by nishanil** [comment]
@DuanShaolong It could be an interim issue. I checked, the same link works. 
https://dotnet.microsoft.com/download/e-book/microservices-architecture/pdf
