### ISSUE TITLE
[Book Feedback] Modernizing Desktop Apps on Windows 10 with .NET Core 3.1 [PDF Version]

### ISSUE THREAD

**Issue by mlemaudit** [dotnet-architecture/eBooks#35]
Modernizing Desktop Apps on Windows 10 with .NET Core 3.1

Pdf Edition only

Page 6 (13/73)
![page_6](https://user-images.githubusercontent.com/5759027/85926829-5a743780-b8a2-11ea-9c19-4c4bf00d77a2.jpg)
- paragraph numbering seems wrong: 1 followed by 1 instead of 2

- 2 missing images

Regards,
M

**Comment by sughosneo** [comment]
Hi @mlemaudit, thank you for your feedback. 
It has been fixed in the latest PDF. Could you please download the latest from [here](https://dotnet.microsoft.com/download/e-book/modernizing-existing-desktop-apps/pdf)? 

I am closing this issue as of now. Please feel free reopen if needed.
