### ISSUE TITLE
[Book Feedback] ASP.NET Core gRPC for WCF Developers

### ISSUE THREAD

**Issue by jtattermusch** [dotnet-architecture/eBooks#4]
**Please provide the title of the book**
ASP.NET Core gRPC for WCF Developers

**What do you think could be improved in this book?**

I'll provide quotes from the book and my for each of them.

Quote from the book:
https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/grpc-overview
*...general purpose RPC infrastructure. Stubby, renamed gRPC, now could take advantage of standardization and would extend its...*

Accuracy: technically stubby hasn't been renamed to gRPC. gRPC is a completely different code base rewritten from scratch, learning from long history of stubby at google and heavily inspired by many of its feature (and also avoiding some of its problems)

---

Quote from the book:
https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/why-grpc
*As already discussed, using HTTP/2 rather than HTTP/1.1 removes the requirement for human-readable messages and instead uses the smaller faster binary protocol. ...*

Accuracy:
I think the overall message is ok, but it's mixing up two concepts: 1. HTTP/2 binary framing which makes http itself more efficient and easier to parse vs HTTP1.1 being a text based protocol 2. whether the actual payloads/messages are binary or not (you can have a binary protobuf payload with HTTP1.1, but you won't have other advantages of HTTP2)

---

Quote from the book:
https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/why-grpc
*...gRPC allows clients to specify a maximum time for an RPC to complete. If the specified deadline is exceeded the server can cancel the operation independently of the client...*

Fine to leave as is, but technically speaking when the deadline is exceeded, both server and client will cancel and be notified of it (due to clock differences one partly can cancel slightly sooner than the other one and grpc internal logic needs to handle that correctly). 

---

The section "how protobuf works" here https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protocol-buffers  feels like it focuses too much on serialization speed and efficiency, but doesn't really mention one of the protobuf's biggest features: the extensibility. Protobuf gives people the ability do develop evolving APIs while maintaining 100% backward compatibility of their services (which in some respect is more important than pure speed, big portion of userbase cares about usability not speed).

---

Quote from the book:
https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-messages
*...Note that the Protobuf compiler applied PascalCase to the property names although they were camelCase in the .proto file. It's best to use camelCase in the message definition so that the code generation for other platforms produces the expected case for their conventions...*

Accuracy: Actually, according to the protobuf code style, the field names should be `lower_case_with_underscore`, not camelCase. See e.g. .proto definitions for official google APIs in this repository: https://github.com/googleapis/googleapis/blob/master/google/cloud/vision/v1p2beta1/web_detection.proto

---

Protobuf reserved fields
https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-reserved

My hunch is that the "reserved" keyword is not really used much in practice, it might be 
useful to do a bit of research on how people actually handle this. My understanding is that the most common situation would be that one party has a newer .proto file with a new field and the other party has and older version of the same proto (where the field is missing). The "reserved" scenarios are not that common IMHO. I can find out more information on this if needed.

---

Quote from the book:
*...Metadata is handled using the Metadata class from the Grpc.Core NuGet package. This class can be used with collection initializer syntax....*
https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/metadata

The metadata class is actually in Grpc.Core.Api nuget. (Background: it used to be in Grpc.Core package, but then it was refactored out to a separate package with shared gRPC API. It had to stay under the same namespace Grpc.Core though for backwards compatibility reasons)

**What do you like about this book?**

Overall I got a good impression about both accuracy and usefulness of the book. Thanks for writing this!

**Additional context**

I'm one of the maintainers of the gRPC project and after reading through the book, I had some (mostly minor) comments, as summarized above.

**Comment by jtattermusch** [comment]
FYI @shirhatti  my feedback on the book

**Comment by nishanil** [comment]
Thank You for the feedback, @jtattermusch !! I see that the review comments linked on the docs have been addressed and the issue has been closed. I'm closing this now. Feel free to re-open if anything was missed out.
