### ISSUE TITLE
.Net Microservices Architecture for Containerized .NET Applications

### ISSUE THREAD

**Issue by JustCallMeCodes** [dotnet-architecture/eBooks#7]
.Net Microservices Architecture for Containerized .NET Applications
**What do you think could be improved in this book?**
more about the workflows of the tools. key functionality. 
[...]. 
**What do you like about this book?**
I liked the introduction about docker containers how they run apps and services virtualized sandbox.
**Additional context**
tooling upgrades

**Comment by JustCallMeCodes** [comment]
offgrid infrastructure shipping containers

**Comment by nishanil** [comment]
@JustCallMeCodes Thanks for the feedback. I am not sure I understand the ask "workflows of the tools" here. Can you expand with examples, please? 
Also, check this page https://dotnet.microsoft.com/learn/aspnet/microservices-architecture which includes books on cloud-native tooling and DevOps there. Let me know if that helps?

**Comment by JustCallMeCodes** [comment]
Thanks for the response @nishanil maybe ill delete this.
