### ISSUE TITLE
Microservices ebook not updated to v5

### ISSUE THREAD

**Issue by zappox** [dotnet-architecture/eBooks#70]
The documentation on the docs site:

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/

mentions a new v5 Edition of the book, however the repository is not updated to the new version and the download link still points to the 3.1 version of the book,

**Comment by vip32** [comment]
https://github.com/dotnet-architecture/eBooks/blob/master/archives/microservices/NET-Microservices-Architecture-for-Containerized-NET-Applications-v3.1.3.pdf

**Comment by sughosneo** [comment]
Hi @zappox , @vip32 , `.NET Microservices: Architecture for Containerized .NET Applications` eBook has been updated to the `.NET 5`. Please download the latest from the [Downloads PDF](https://aka.ms/microservicesebook) link.

**Comment by vip32** [comment]
Hi @sughosneo,  will the epub also be available again?

**Comment by sughosneo** [comment]
Hi @vip32, we used to maintain this `epub` version earlier, but due to low downloads, we have stopped maintaining this version along with PDFs. If anyone from the community wishes to convert the PDF to the `epub` version and submits a PR, we'll be happy to review and host it with our PDFs.

**Comment by nishanil** [comment]
Closing this issue now. We may look at mobile versions in the future when demand is higher.
