### ISSUE TITLE
[Book Feedback]

### ISSUE THREAD

**Issue by kitdotnet** [dotnet-architecture/eBooks#74]
Title: NET-Microservices-Architecture-for-Containerized-NET-Applications.pdf

The following sentence on p. 20 needs re-wording: 
So, when you “look” at the filesystem after the layer has been copied, you see all the files, **included** the layer when the program was installed.

Perhaps they meant "... included in the layer..." ?

**Additional context**
Add any other context or screenshots about your feedback.

**Comment by erjain** [comment]
I am closing this issue as of now. Please feel free to reopen it, if needed.
