### ISSUE TITLE
[Book Feedback]

### ISSUE THREAD

**Issue by mizrael** [dotnet-architecture/eBooks#89]
**Please provide the title of the book**
Dapr for .NET Developers

**What do you think could be improved in this book?**
would it be possible to have an e-book friendly version as well? Like .mobi or .epub

**Comment by sughosneo** [comment]
Hi @mizrael, thank you for your feedback. 
It has been answered in https://github.com/dotnet-architecture/eBooks/issues/70#issuecomment-902036563

I am closing this issue as of now. Please feel free to reopen if needed.
