### ISSUE TITLE
[Book Feedback]

### ISSUE THREAD

**Issue by moldyseaswimmer** [dotnet-architecture/eBooks#9]
**Please provide the title of the book**
"Architecting Cloud-Native .NET Apps for Azure". 

**What do you think could be improved in this book?**
Provide a Service Fabric or Dapr implementation example that can run on premises or cloud. Containers are not always a preferred option.

**What do you like about this book?**
N/A

**Additional context**
N/A

**Comment by robvet** [comment]
Great suggestion. We are discussing adding a chapter that would feature DAPR and OAM. 

Being a cloud native book, we're highly focused on cloud implementation and not so much on-prem, which would be a different book.

Please stay-tuned.

**Comment by robvet** [comment]
Thanks so much for the suggestions. In the upcoming version 2 Cloud Native eBook, we'll discuss Service Fabric in Chapter 3, which will change names from "Scaling Cloud-Native .NET Apps" to "Hosting Cloud-Native .NET apps."

We'll also mention Dapr in Chapter 1 and make frequent references to it in the accompanying chapters. However, for a full reference implementation for Dapr, please see the '[Dapr for .NET Developers](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/?WT.mc_id=dotnet-35129-website)' eBook, which contains an updated version of eShop running with Dapr.
