### ISSUE TITLE
Mobile source code link needs updated.

### ISSUE THREAD

**Issue by DynamicCafeSolutions** [dotnet-architecture/eBooks#98]
![Screenshot_20210406-200353_Chrome Dev.jpg](https://user-images.githubusercontent.com/56435805/113792148-d7beb980-970a-11eb-9a11-6249c3deac96.jpg)

The link titled "Sample App" needs to be changed:

The old link

https://github.com/dotnet-architecture/eShopOnContainers/tree/master/src/Mobile

Should be

https://github.com/dotnet-architecture/eshop-mobile-client

**Comment by nishanil** [comment]
@DynamicCafeSolutions Thanks for pointing this out. We have fixed the references on the website. https://dotnet.microsoft.com/learn/xamarin/architecture 
Closing this issue now.
